package com.aad.ffsmart.order;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Order service
 * <p>
 * Contains order method signatures, implemented in OrderServiceImpl
 *
 * @author Oliver Wortley
 */
public interface OrderService {

    Mono<Order> createOrder(Order order, boolean autoGenerated);

    Flux<Order> getAllOrders(OrderStatus status);

    Flux<Order> getMyOrders(String userId);

    Flux<Order> getReadyOrders();

    Flux<Order> getApprovedOrders();

    Mono<Order> getOrderById(String orderId);

    Mono<Void> rejectOrder(String orderId);

    Mono<Order> approveOrder(String orderId);

    Mono<Order> dispatchOrder(String orderId, String userId);

    Mono<Order> deliverOrder(String orderId);
}
