package com.aad.ffsmart.order;

import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.Map;

/**
 * Order status enum
 * <p>
 * Defines 4 statuses for orders:
 * - READY -> generated by system successfully, ready for approval
 * - APPROVED -> approved by head chef and sent to supplier
 * - IN_TRANSIT -> selected by delivery driver to collect and deliver
 * - DELIVERED -> order delivered and items added to fridge inventory
 *
 * @author Oliver Wortley
 */
public enum OrderStatus {
    READY(0),
    APPROVED(1),
    IN_TRANSIT(2),
    DELIVERED(3);

    public final int value;
    private static Map<Integer, OrderStatus> map = new HashMap<>();

    static {
        for (OrderStatus pageType : OrderStatus.values()) {
            map.put(pageType.value, pageType);
        }
    }

    private OrderStatus(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    public static OrderStatus fromValue(int value) {
        return map.get(value);
    }

}
